export const ALL_SEATS =[
    {
        "seatId": 15390,
        "seatNo": "EN-1",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 1,
        "yaxis": 3
    },
    {
        "seatId": 15391,
        "seatNo": "EN-2",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 1,
        "yaxis": 4
    },
    {
        "seatId": 15392,
        "seatNo": "EN-3",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 2,
        "yaxis": 3
    },
    {
        "seatId": 15393,
        "seatNo": "EN-4",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 2,
        "yaxis": 4
    },
    {
        "seatId": 15394,
        "seatNo": "A-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 3,
        "yaxis": 1
    },
    {
        "seatId": 15395,
        "seatNo": "A-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 3,
        "yaxis": 2
    },
    {
        "seatId": 15396,
        "seatNo": "A-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 3,
        "yaxis": 4
    },
    {
        "seatId": 15397,
        "seatNo": "A-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 3,
        "yaxis": 5
    },
    {
        "seatId": 15398,
        "seatNo": "B-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 4,
        "yaxis": 1
    },
    {
        "seatId": 15399,
        "seatNo": "B-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 4,
        "yaxis": 2
    },
    {
        "seatId": 15400,
        "seatNo": "B-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 4,
        "yaxis": 4
    },
    {
        "seatId": 15401,
        "seatNo": "B-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 4,
        "yaxis": 5
    },
    {
        "seatId": 15402,
        "seatNo": "C-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 5,
        "yaxis": 1
    },
    {
        "seatId": 15403,
        "seatNo": "C-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 5,
        "yaxis": 2
    },
    {
        "seatId": 15404,
        "seatNo": "C-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 5,
        "yaxis": 4
    },
    {
        "seatId": 15405,
        "seatNo": "C-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 5,
        "yaxis": 5
    },
    {
        "seatId": 15406,
        "seatNo": "D-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 6,
        "yaxis": 1
    },
    {
        "seatId": 15407,
        "seatNo": "D-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 6,
        "yaxis": 2
    },
    {
        "seatId": 15408,
        "seatNo": "D-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 6,
        "yaxis": 4
    },
    {
        "seatId": 15409,
        "seatNo": "D-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 6,
        "yaxis": 5
    },
    {
        "seatId": 15410,
        "seatNo": "E-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 7,
        "yaxis": 1
    },
    {
        "seatId": 15411,
        "seatNo": "E-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 7,
        "yaxis": 2
    },
    {
        "seatId": 15412,
        "seatNo": "E-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 7,
        "yaxis": 4
    },
    {
        "seatId": 15413,
        "seatNo": "E-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 7,
        "yaxis": 5
    },
    {
        "seatId": 15414,
        "seatNo": "F-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 8,
        "yaxis": 1
    },
    {
        "seatId": 15415,
        "seatNo": "F-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 8,
        "yaxis": 2
    },
    {
        "seatId": 15416,
        "seatNo": "F-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 8,
        "yaxis": 4
    },
    {
        "seatId": 15417,
        "seatNo": "F-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 8,
        "yaxis": 5
    },
    {
        "seatId": 15418,
        "seatNo": "G-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 9,
        "yaxis": 1
    },
    {
        "seatId": 15419,
        "seatNo": "G-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 9,
        "yaxis": 2
    },
    {
        "seatId": 15420,
        "seatNo": "G-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 9,
        "yaxis": 4
    },
    {
        "seatId": 15421,
        "seatNo": "G-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 9,
        "yaxis": 5
    },
    {
        "seatId": 15422,
        "seatNo": "H-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 10,
        "yaxis": 1
    },
    {
        "seatId": 15423,
        "seatNo": "H-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 10,
        "yaxis": 2
    },
    {
        "seatId": 15424,
        "seatNo": "H-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 10,
        "yaxis": 4
    },
    {
        "seatId": 15425,
        "seatNo": "H-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 10,
        
        "yaxis": 5
    },
    {
        "seatId": 15426,
        "seatNo": "I-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 11,
        "yaxis": 1
    },
    {
        "seatId": 15427,
        "seatNo": "I-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 11,
        "yaxis": 2
    },
    {
        "seatId": 15428,
        "seatNo": "I-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 11,
        "yaxis": 4
    },
    {
        "seatId": 15429,
        "seatNo": "I-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 11,
        "yaxis": 5
    },
    {
        "seatId": 15430,
        "seatNo": "J-1",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 12,
        "yaxis": 1
    },
    {
        "seatId": 15431,
        "seatNo": "J-2",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 12,
        "yaxis": 2
    },
    {
        "seatId": 15432,
        "seatNo": "J-3",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 12,
        "yaxis": 4
    },
    {
        "seatId": 15433,
        "seatNo": "J-4",
        "seatTypeId": "E-Class",
        "status": "Available",
        "colorCode": "#ffffff",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 12,
        "yaxis": 5
    },
    {
        "seatId": 15434,
        "seatNo": "K-1",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 13,
        "yaxis": 1
    },
    {
        "seatId": 15435,
        "seatNo": "K-2",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 13,
        "yaxis": 2
    },
    {
        "seatId": 15436,
        "seatNo": "K-3",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 13,
        "yaxis": 3
    },
    {
        "seatId": 15437,
        "seatNo": "K-4",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 13,
        "yaxis": 4
    },
    {
        "seatId": 15438,
        "seatNo": "K-5",
        "seatTypeId": "E-Class",
        "status": "Blocked",
        "colorCode": "#aaaaaa",
        "fare": "650.00",
        "deckTitle": null,
        "xaxis": 13,
        "yaxis": 5
    }
]