export const VEHICLE = [
  {
    id: 1,
    name: 'Motor Cycle',
    code: 'MCL',
    img: null,
    price: 0,
    description: null,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 2,
    name: 'Private Car',
    code: 'PCR',
    description: null,
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 3,
    name: 'Pickup',
    code: 'SPIC',
    description: '(length 7 feet (4 wheels))',
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 4,
    name: 'Luxury Car',
    code: 'LUXCR',
    description: null,
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 5,
    name: 'Micro Bus',
    code: 'SMICBS',
    description: '(Microbus (Hayes, Noah, others))',
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 6,
    name: 'Medium Pickup',
    code: 'MPIC',
    description: '(length 7-9 feet (6 wheels))',
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 7,
    name: 'Large Pickup',
    code: 'LPIC',
    description: '(length 12-16 feet (6 wheels))',
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 8,
    name: 'Large Pickup',
    code: 'XLPIC',
    description: '(length 16-24 feet (6 wheels))',
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 9,
    name: 'Mini Bus',
    code: 'MINBS',
    description: null,
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
  {
    id: 10,
    name: 'Large Bus',
    code: 'LGBS',
    description: null,
    img: null,
    price: 0,
    totalSeat: 0,
    priority: 1,
  },
];
